
development:
  adapter: postgresql
  database: directory-alpha_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: directory-alpha_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: directory-alpha_production
  pool: 5
  timeout: 5000
